### PR TITLE
fix typos, various improvements

### PR DESCRIPTION
**Pull request by descodess**
- fix typos (see: https://en.wikipedia.org/wiki/Coordinated_Universal_Time, https://de.wikipedia.org/wiki/Durchkopplung, https://www.duden.de/sprachwissen/rechtschreibregeln)
- add/improve/unify hyperlinks
- improve readability
- various unifications

### CODE REVIEW

**Review by mhei — COMMENTED** [review]
I like this PR. All changes looks good so far, only one note: I'm not sure about the real name of the referenced MEMO-GL "...Sicherungskonzept..." vs. "...Sicherheitskonzept..." - both names makes sense to me and I cannot find the document on public Internet.
If nobody can confirm that the change is correct, I'd vote to leave this one out.

And maybe another note: I hope you noticed the ongoing work to translate the document to English. Once finished, this German version will be dropped.

**Review by FlorianRieglerKeba — APPROVED** [review]

**Comment by FlorianRieglerKeba** [comment]
Could you please revert the one change renaming "...Sicherungskonzept..." to "...Sicherheitskonzept...". This was discussed in the subgroup to leave it as it is.

**Comment by mhei** [comment]
@descodess : ping?

**Comment by mhei** [comment]
No response, so I created a new PR #22 which supersedes this one. When #22 is merged, this PR can be closed.

**Pull request closed without merging**
